# Generated by Django 4.0.1 on 2022-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_pwd', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
